cluster.name: opensearch-cluster
network.host: 0.0.0.0

discovery.seed_hosts: opensearch-node1,opensearch-node2,opensearch-node3 # Nodes to look for when discovering the cluster
cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2,opensearch-node3 # Nodes eligibile to serve as cluster manager

bootstrap.memory_lock: true # Disable JVM heap memory swapping

plugins.security.disabled: false

plugins.security.ssl.transport.pemcert_filepath: certificates/os/os.pem
plugins.security.ssl.transport.pemkey_filepath: certificates/os/os.key
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certificates/os/os.pem
plugins.security.ssl.http.pemkey_filepath: certificates/os/os.key
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/root-ca.pem
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - "CN=ADMIN,OU=AC,O=AC,L=AC,ST=AC,C=AC"
plugins.security.nodes_dn:
  - "CN=os,OU=AC,O=AC,L=AC,ST=AC,C=AC"

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.cache.ttl_minutes: 60
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
node.max_local_storage_nodes: 3
